run_name: wm_debug_bs_32_
# from_checkpoint: ./checkpoint/cdit_xl_ego4d_200000.pth.tar  # resume from latest.pth.tar instead
# training setup
results_dir: logs
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 4
num_workers: 12
model: CDiT-XL/2
lr: 8e-5
cross_attend: 0

# normalization for the action space
normalize: True
grad_clip_val: 10.0
# context
context_size: 4

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: -64
  max_dist_cat: 64

# action output params
len_traj_pred: 64

# dataset specific parameters
image_size: 224
datasets:
  bunker2025:
      data_folder: /project/pi_hzhang2_umass_edu/suyoungkang_umass_edu/Git/nwm/data/bunker2025
      train: /project/pi_hzhang2_umass_edu/suyoungkang_umass_edu/Git/nwm/data_splits/bunker2025
      test: /project/pi_hzhang2_umass_edu/suyoungkang_umass_edu/Git/nwm/data_splits/bunker2025
      goals_per_obs: 4